// <auto-generated />
namespace Eahara.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class jishnuemp1110182 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(jishnuemp1110182));
        
        string IMigrationMetadata.Id
        {
            get { return "201810110927539_jishnuemp1110182"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
