// <auto-generated />
namespace Eahara.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class empty2112018 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(empty2112018));
        
        string IMigrationMetadata.Id
        {
            get { return "201901210603078_empty21-1-2018"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
